sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: s1VehHkykecANsd+ZqVKEEHpERER4cp59CEo+LAsXR05pYAPKvH7kL6He2TI+596TXprnwZwYDYLd8zLtvHnT4sbJ3xJSZtpnGyGIeSx1xrVXAPLLcCiyjib5ENJwLtIHPC+chPgytlSWs0GhOOyrUk1mNYQLd62d+6P6Jn8nVYvAkbCQgu4afRkAlbz6yaJA3CWCZCHCXDOjxg7sl3Fu91SamJoLvEYYGUF36G3AaWVl/OX00KsvRBcO0hc36zJlf5fPmajGzdrYbKjXRFpCxJPktK63MmmzkFomtk7oiFX9wT8ULAEC8NohJ5QxTl/G3w2BteDasIn4OMs/zmcfch3QeUPuzjFyn70gfX2H/xzCWxMPfzEpxPOblOEd5Onx1/NTs/KDMlY/3Tvoi3pmlvTyM0GKSCqY8d08c+SimbpyLqrHZ+8SOnZvPuioD8rJPFF2+swK/ZBJji1/jvrCtC9tmmb5PbOVlNd/VG1GTXwytRDRlF0R+sxw69uTmqF7q/skxqnB8TubtP8DBSKJTx/su0diEsBjEDldexiS2azgs8bMDpGy6bMe7hIzuqbvx2QoHJineq12EMtHYJAg0+OF401xkGf8koL03injBox3MVw5NkIFz/bMDNrd0Wg2s3eumJ5uKRvexSckvG1pDQvQbs7Ql3vkgiYOtx9tlg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Great-Jehoshaphat-and-Gully-Dirt_2357
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy